baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'iMoment'

[outputFormats]
  [outputFormats.CustomList]
    mediaType = "text/html"
    baseName = "customlist"
    isHTML = true

[outputs]
  section = ["HTML", "CustomList"]
