baseURL = 'https://junhyuncho.github.io/imoment-bs-hugo-notheme/'
languageCode = 'en-us'
title = 'iMoment'

[outputFormats]
  [outputFormats.MapList]
    mediaType = "text/html"
    baseName = "maplist"
    isHTML = true

  [outputFormats.KeywordList]
    mediaType = "text/html"
    baseName = "keywordlist"
    isHTML = true

  [outputFormats.LocationList]
    mediaType = "text/html"
    baseName = "locationlist"
    isHTML = true

[outputs]
  section = ["HTML", "MapList", "KeywordList", "LocationList"]
